### PR TITLE
Added API route

### PR DESCRIPTION
**Pull request by liulanz**
Added API route

- [x] runs successfully
- [x]  tested on postman
// make sure you type the password in next.config.js to test it

**POST:**
post-screenshot

**GET:**
get-screenshot

### CODE REVIEW

**Review by sdhani — APPROVED** [review]
Looks good!

**Review by MichelleLucero — COMMENTED** [review]
Great job! I'm wondering if an [id].js  is necessary to add?? I'm not sure. Let me know if you know the answer!

**Review by MichelleLucero — APPROVED** [review]

**Comment by sdhani** [comment]
@MichelleLucero I think you are right. I don't think it's here, but for future reference, we probably don't need to include Next.js dynamic routing in the example. :+1:

**Review by chislee0708 — APPROVED** [review]
Great！

**Pull request merged**
