### PR TITLE
added with-mongodb directory

### PR DESCRIPTION
**Pull request by liulanz**
Started MongoDB+Next.js example by running npx create-next-app with-mongodb

with-mongodb directory now contains a default application template

### CODE REVIEW

**Review by sdhani — CHANGES_REQUESTED** [review]
Hey @liulanz , the project initialization looks good! It does pass through an empty directory however. I suggest creating the `with-mongodb` directory in the examples root folder instead of inside the `with-mongodb` folder so that it is consistent with the other examples.

So the final directory structure should look something like this:
`/examples/with-mongodb/pages`

instead of 

`/examples/with-mongodb/with-mongodb/pages`

Great project structure!!

**Comment by liulanz** [comment]
@sdhani I didn't realize that I did that. Sorry about that. I've deleted the extra directory.

**Comment by liulanz** [comment]
I added a readme template based on the template that was provided on Next.js repo

**Comment by sdhani** [comment]
Awesome this looks great!! Thanks for jumping on this :blush::100:

**Review by sdhani — APPROVED** [review]

**Comment by liulanz** [comment]
I will close this PR because it contains other files changes. I was being lazing to add every file in with-mongodb directory, so I did "git add . ". I'll open another PR with only with-mongodb directory added. Sorry about that.

**Pull request closed without merging**
